local_backend: true
backend:
  name: git-gateway
  branch: main

media_folder: src/uploads
public_folder: /uploads
site_url: http://localhost:8080
locale: ro
publish_mode: editorial_workflow

collections:
  - name: index
    label: Global config
    extension: json
    create: false
    delete: false
    slug: "{{slug}}"
    files:
      - label: Home Page
        name: home
        file: src/_data/config/home.json
        fields:
          - label: Layout
            name: layout
            widget: hidden
            default: index.njk

          - label: Titlu pagina
            name: title
            widget: string

          - label: Antent principal
            name: heroHeader
            widget: text

          - label: Subtitlu antent principal
            name: heroHeaderCaption
            widget: markdown

          - label: Descriere antent principal
            name: heroDescription
            widget: markdown

          - label: Link antent principal
            name: heroLink
            widget: string

          - label: Link text antet principal
            name: heroLinkText
            widget: string

          - label: Imagine antet principal
            name: heroImage
            widget: image

          - label: Descriere imagine antet principal
            name: heroImageAlt
            widget: text

          - label: Antet sectiune "features"
            name: featuresHeader
            widget: string

          - label: Antet sectiune "featured pages"
            name: featuredPagesHeader
            widget: string

      - label: Sidebar
        name: sidebar
        file: src/_data/config/sidebar.json
        fields:
          - label: Layout
            name: layout
            widget: hidden
            default: sidebar.njk

          - label: Permalink
            name: permalink
            widget: hidden
            default: false

          - label: Titlu sectiune "Sidebar features"
            name: featuresTitle
            widget: string

          - label: Contact
            name: contact
            widget: object
            fields:
              - label: Antet
                name: header
                widget: string

              - label: Descriere
                name: description
                widget: markdown
                required: false

              - label: Email
                name: email
                widget: string

              - label: Telefon
                name: phone
                widget: string

              - label: Adresa
                name: address
                widget: string

          - label: Copyright
            name: copyright
            widget: markdown

      - label: Social
        name: social
        file: src/_data/config/social.json
        fields:
          - label: Antent
            name: header
            widget: object
            fields:
              - label: Text principal
                name: main
                widget: string

              - label: Text secundar
                name: sub
                widget: string
                required: false

          - label: Facebook URL
            name: facebook
            widget: string
            required: false

  - name: page
    label: Page
    folder: src/pages
    create: true
    slug: "{{slug}}"
    fields:
      - label: Titlu
        name: title
        widget: string

      - label: Continut
        name: body
        widget: markdown
        required: false

      - label: Descriere
        name: excerpt
        widget: text
        required: false

      - label: Imagine
        name: image
        widget: image
        required: false

      - label: Featured
        name: isFeatured
        widget: boolean
        default: false

      - label: Link permanent
        name: permalink
        widget: boolean
        required: false
        default: true
        hint: Nu debifati aceasta optiune decat daca folositi optiunea URL de la Configurare meniu

      - label: Configurare meniu
        name: eleventyNavigation
        widget: object
        fields:
          - label: Cheie
            name: key
            widget: string

          - label: Cheie parinte
            name: parent
            widget: string
            required: false
            hint: "Daca aceasta optiune nu este setata
              pagina nu va putea fi accesata. Paginile parinte sunt folosite doar pentru a grupa alte paginin
              nu pentru a afisa continut"

          - label: Titlu alternativ pentru meniu
            name: title
            widget: string
            required: false

          - label: Ordine
            name: order
            widget: number
            default: 1

          - label: URL
            name: url
            widget: string
            required: false
            hint: Folosit pentru linkuri externe. **Setati "Link permanent" la `fals`**.

  - name: home-feature
    label: Home feature
    folder: src/home-features
    create: true
    slug: "{{slug}}"
    fields:
      - label: Icon
        name: icon
        widget: string
        hint: "[Lista iconite](https://fontawesome.com/v5.15/icons?d=gallery&p=2&m=free). Ex: `fa-edit`"

      - label: Title
        name: title
        widget: string

      - label: Body
        name: body
        widget: markdown

  - name: sidebar-feature
    label: Sidebar feature
    folder: src/sidebar-features
    create: true
    slug: "{{slug}}"
    fields:
      - label: Titlu
        name: title
        widget: string

      - label: URL
        name: url
        widget: string

      - label: Imagine
        name: image
        widget: image
        required: false

      - label: Body
        name: body
        widget: markdown
