# local_backend: true
# site_url: http://localhost:8080

backend:
  name: git-gateway
  branch: main

media_folder: /uploads
public_folder: /uploads
locale: ro
# publish_mode: editorial_workflow

collections:
  - name: global-config
    label: Configuratie globala
    extension: json
    create: false
    delete: false
    slug: "{{slug}}"
    files:
      - label: Pagina de start
        name: config-home
        file: src/_data/config/home.json
        fields:
          - label: Layout
            name: layout
            widget: hidden
            default: index.njk

          - label: Titlu pagina
            name: title
            widget: string

          - label: Antent principal
            name: heroHeader
            widget: text

          - label: Subtitlu antent principal
            name: heroHeaderCaption
            widget: markdown
            required: false

          - label: Descriere antent principal
            name: heroDescription
            widget: markdown
            required: false

          - label: Link antent principal
            name: heroLink
            widget: string
            required: false

          - label: Link text antet principal
            name: heroLinkText
            widget: string
            required: false

          - label: Imagine antet principal
            name: heroImage
            widget: image

          - label: Descriere imagine antet principal
            name: heroImageAlt
            widget: text
            required: false

          - label: Antet sectiune "features"
            name: featuresHeader
            widget: string
            required: false

          - label: Antet sectiune "featured pages"
            name: featuredPagesHeader
            widget: string
            required: false

          - label: Text buton "featured"
            name: featuredButtonText
            widget: string
            required: false

      - label: Sidebar
        name: config-sidebar
        file: src/_data/config/sidebar.json
        fields:
          - label: Layout
            name: layout
            widget: hidden
            default: sidebar.njk

          - label: Permalink
            name: permalink
            widget: hidden
            default: false

          - label: Titlu meniu
            name: menuHeader
            widget: string

          - label: Text link acasa
            name: homeMenuItemText
            widget: string

          - label: Titlu sectiune "Sidebar features"
            name: featuresTitle
            widget: string

          - label: Contact
            name: contact
            widget: object
            fields:
              - label: Antet
                name: header
                widget: string
                required: false

              - label: Descriere
                name: description
                widget: markdown
                required: false

              - label: Email
                name: email
                widget: string
                required: false

              - label: Telefon
                name: phone
                widget: string
                required: false

              - label: Adresa
                name: address
                widget: string
                required: false

          - label: Copyright
            name: copyright
            widget: markdown
            required: false

      - label: Social
        name: config-social
        file: src/_data/config/social.json
        fields:
          - label: Antent
            name: header
            widget: object
            fields:
              - label: Text principal
                name: main
                widget: string

              - label: Text secundar
                name: sub
                widget: string
                required: false

          - label: Facebook URL
            name: facebook
            widget: string
            required: false

      - label: Erori
        name: config-errors
        file: src/_data/config/errors.json
        fields:
          - label: Eroare 404
            name: http_404
            widget: object
            fields:
              - label: Text principal
                name: header
                widget: markdown

  - name: page
    label: Pagini
    folder: src/pages
    create: true
    slug: "{{slug}}"
    fields:
      - label: Titlu
        name: title
        widget: string

      - label: Continut
        name: body
        widget: markdown
        required: false

      - label: Imagine sau fisier
        name: file
        widget: file
        required: false

      - label: Descriere fisier
        name: fileAlt
        widget: string
        required: false

      - label: Featured
        name: featured
        widget: object
        fields:
          - label: Featured
            name: isFeatured
            widget: boolean
            required: false
            default: false

          - label: Imagine pentru featured widget
            name: image
            widget: image
            required: false

          - label: Descriere imagine featured widget
            name: imageAlt
            widget: string
            required: false

          - label: Descriere
            name: excerpt
            widget: text
            required: false

      - label: Link permanent
        name: permalink
        widget: boolean
        required: false
        default: true
        hint: Nu debifati aceasta optiune decat daca folositi optiunea URL de la Configurare meniu

      - label: Configurare meniu
        name: eleventyNavigation
        widget: object
        fields:
          - label: Nume
            name: key
            widget: string
            hint: 'Un nume unic folosit pentru gruparea in meniul din stanga.
              Acest text va fi folosit pentru afisare in meniu daca nu este
              suprascris de "Titlu alternativ pentru meniu"'

          - label: Nume parinte
            name: parent
            widget: string
            required: false
            hint:
              "Daca aceasta optiune nu este setata si exista alte pagini care o au pe aceasta ca si parinte,
              pagina nu va putea fi accesata. Paginile parinte sunt folosite doar pentru a grupa alte paginin
              nu pentru a afisa continut"

          - label: Titlu alternativ pentru meniu
            name: title
            widget: string
            required: false

          - label: Ordine
            name: order
            widget: number
            default: 1

          - label: URL
            name: url
            widget: string
            required: false
            hint: Folosit pentru linkuri externe. **Setati "Link permanent" la `fals`**.

  - name: home-feature
    label: Home features
    folder: src/home-features
    create: true
    slug: "{{slug}}"
    fields:
      - label: Icon
        name: icon
        widget: string
        hint: "Click [aici](https://fontawesome.com/v5.15/icons?d=gallery&p=2&m=free) pentru lista iconite. Exemplu: `fa-edit`"

      - label: Title
        name: title
        widget: string

      - label: Body
        name: body
        widget: markdown

  - name: sidebar-feature
    label: Sidebar features
    folder: src/sidebar-features
    create: true
    slug: "{{slug}}"
    fields:
      - label: Titlu
        name: title
        widget: string

      - label: URL
        name: url
        widget: string

      - label: Imagine
        name: image
        widget: image
        required: false

      - label: Body
        name: body
        widget: markdown
